parent=base
import=common/keycloak

meta=viewport==width=device-width,initial-scale=1

styles=css/esigmap.css css/boxicons.min.css css/reset-flow.css
scripts=js/script.js js/esigmap.js js/password-toggle.js js/jquery.min.js js/alpine.mini.js js/reset-flow.js

